name: Push server_money.json

on:
  workflow_dispatch:
    inputs:
      json_data:
        description: 'JSONデータ文字列'
        required: true
        type: string

jobs:
  push_json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (without default credentials)
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Save input JSON to file
        run: |
          echo '${{ github.event.inputs.json_data }}' > server_money.json

      - name: Commit and push with PAT
        env:
          TOKEN: ${{ secrets.GH_PUSH_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git
          git add server_money.json
          git commit -m "Update money data [auto]" || echo "No changes to commit"
          git push origin main
