name: Push server_money.json

on:
  workflow_dispatch:
    inputs:
      json_data:
        description: 'JSON string from bot'
        required: true

jobs:
  push_json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (no credentials)
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Save input JSON to file
        run: |
          echo "${{ github.event.inputs.json_data }}" > server_money.json

      - name: Commit and push with PAT
        env:
          TOKEN: ${{ secrets.GH_PUSH_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git
          
          # 作業中の変更を一時退避
          git stash --include-untracked
          
          # 最新のリモートブランチを取得
          git pull --rebase origin main
          
          # 退避した変更を戻す
          git stash pop || echo "Nothing to pop"

          git add server_money.json
          git commit -m "Update money data [auto]" || echo "No changes to commit"
          git push origin main
