name: Push server_money.json

on:
  workflow_dispatch:
    inputs:
      json_data:
        description: 'Money JSON data'
        required: true

jobs:
  save_data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Save JSON to file
        run: |
          echo '${{ github.event.inputs.json_data }}' > server_money.json
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add server_money.json
          git commit -m "Auto update server_money.json"
          git push
